import { PlaceDetail, PlaceSummary, ResolveState } from '@/lib/types';

export const featuredPlaces: PlaceSummary[] = [
  {
    id: 'plc_royal-bark',
    slug: 'royal-bark-cafe',
    name: 'Royal Bark Cafe',
    formattedAddress: '12 Napier St, Fitzroy VIC',
    category: 'Cafe',
    distanceLabel: '6 min away',
    dogPolicyStatus: 'restricted',
    confidenceLabel: 'High confidence',
    verifiedAtLabel: 'Checked 2 days ago',
    summary: 'Courtyard-friendly with leash-on entry rules.',
  },
  {
    id: 'plc_pawsome-park',
    slug: 'pawsome-park',
    name: 'Pawsome Park',
    formattedAddress: '88 River Walk, Richmond VIC',
    category: 'Park',
    distanceLabel: '14 min away',
    dogPolicyStatus: 'allowed',
    confidenceLabel: 'Verified',
    verifiedAtLabel: 'Checked today',
    summary: 'Off-leash area with fenced community lawn.',
  },
  {
    id: 'plc_market-hall',
    slug: 'market-hall-grocer',
    name: 'Market Hall Grocer',
    formattedAddress: '40 Smith St, Collingwood VIC',
    category: 'Retail',
    distanceLabel: '18 min away',
    dogPolicyStatus: 'unknown',
    confidenceLabel: 'Needs verification',
    verifiedAtLabel: 'No trusted source yet',
    summary: 'Looks promising, but published policy is still unknown.',
  },
];

export const placeDetailsById: Record<string, PlaceDetail> = {
  'plc_royal-bark': {
    id: 'plc_royal-bark',
    slug: 'royal-bark-cafe',
    name: 'Royal Bark Cafe',
    formattedAddress: '12 Napier St, Fitzroy VIC',
    category: 'Cafe',
    summary: 'Neighbourhood cafe with a dog-friendly courtyard and clear leash guidance.',
    websiteUrl: 'https://example.com/royal-bark',
    petRules: {
      dogPolicyStatus: 'restricted',
      indoorAllowed: false,
      outdoorAllowed: true,
      leashRequired: true,
      sizeRestriction: null,
      breedRestriction: null,
      serviceDogOnly: false,
      notes: 'Dogs are welcome in the courtyard. Staff may pause access during busy brunch periods.',
      confidenceLabel: 'High confidence',
      verificationSourceType: 'official_website',
      verificationSourceLabel: 'Official website',
      verificationSourceUrl: 'https://example.com/royal-bark/policy',
      verifiedAtLabel: 'Last checked 12 Mar 2026',
    },
  },
  'plc_pawsome-park': {
    id: 'plc_pawsome-park',
    slug: 'pawsome-park',
    name: 'Pawsome Park',
    formattedAddress: '88 River Walk, Richmond VIC',
    category: 'Park',
    summary: 'Large green space with an off-leash section and water stations near the oval.',
    websiteUrl: 'https://example.com/pawsome-park',
    petRules: {
      dogPolicyStatus: 'allowed',
      indoorAllowed: null,
      outdoorAllowed: true,
      leashRequired: false,
      sizeRestriction: null,
      breedRestriction: null,
      serviceDogOnly: false,
      notes: 'Off-leash allowed inside the signed exercise area. Leash required on shared paths.',
      confidenceLabel: 'Verified',
      verificationSourceType: 'onsite_signage',
      verificationSourceLabel: 'On-site signage',
      verificationSourceUrl: null,
      verifiedAtLabel: 'Last checked 14 Mar 2026',
    },
  },
  'plc_market-hall': {
    id: 'plc_market-hall',
    slug: 'market-hall-grocer',
    name: 'Market Hall Grocer',
    formattedAddress: '40 Smith St, Collingwood VIC',
    category: 'Retail',
    summary: 'Popular grocery stop with mixed anecdotes but no publishable rule yet.',
    petRules: {
      dogPolicyStatus: 'unknown',
      indoorAllowed: null,
      outdoorAllowed: null,
      leashRequired: null,
      sizeRestriction: null,
      breedRestriction: null,
      serviceDogOnly: null,
      notes: 'We need a stronger source before showing a dog policy.',
      confidenceLabel: 'Needs verification',
      verificationSourceType: null,
      verificationSourceLabel: 'No reliable evidence yet',
      verificationSourceUrl: null,
      verifiedAtLabel: 'Unknown',
    },
  },
};

export const resolveStateBySlug: Record<string, ResolveState> = {
  'royal-bark-cafe': 'ready',
  'pawsome-park': 'ready',
  'market-hall-grocer': 'unknown',
  'google-cache-miss-demo': 'cache_miss',
};

export function getPlaceBySlug(slug: string) {
  return Object.values(placeDetailsById).find((place) => place.slug === slug) ?? null;
}
